python_library()

python_tests(
    name="tests",
)

# add support for requirements.txt
python_requirements()

# enable binary executable generator
pex_binary(
    name="pex_binary",
    entry_point="main.py",
)

